/**
 * GERADO por scripts/vendor-movement-art.mjs — nao editar a mao.
 *
 * O manifesto do workout-guide destilado: slug, musculo primario, equipamento e
 * tipo, sem os 14 alongamentos. O nome em portugues de cada slug esta em
 * `names.pt.ts`, escrito a mao; o vocabulario de traducao esta em
 * `taxonomy.ts`. Metadados do projeto workout-guide de Bryl Lim, MIT.
 */

import type { ExerciseType, GuideEquipment, GuideMuscle } from './taxonomy';

/** `[slug, primaryMuscle, equipment, exerciseType]` */
export type MovementRow = readonly [string, GuideMuscle, GuideEquipment, ExerciseType];

export const MOVEMENT_DATA: readonly MovementRow[] = [
  ['bench-press', 'Chest', 'Barbell', 'weight_reps'],
  ['incline-bench-press', 'Chest', 'Barbell', 'weight_reps'],
  ['incline-dumbbell-press', 'Chest', 'Dumbbell', 'weight_reps'],
  ['dumbbell-bench-press', 'Chest', 'Dumbbell', 'weight_reps'],
  ['decline-bench-press', 'Chest', 'Barbell', 'weight_reps'],
  ['machine-chest-press', 'Chest', 'Machine', 'weight_reps'],
  ['pec-deck', 'Chest', 'Machine', 'weight_reps'],
  ['cable-fly', 'Chest', 'Cable', 'weight_reps'],
  ['push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['weighted-push-up', 'Chest', 'Bodyweight', 'weight_reps'],
  ['overhead-press', 'Shoulders', 'Barbell', 'weight_reps'],
  ['seated-dumbbell-press', 'Shoulders', 'Dumbbell', 'weight_reps'],
  ['arnold-press', 'Shoulders', 'Dumbbell', 'weight_reps'],
  ['lateral-raise', 'Shoulders', 'Dumbbell', 'weight_reps'],
  ['cable-lateral-raise', 'Shoulders', 'Cable', 'weight_reps'],
  ['front-raise', 'Shoulders', 'Dumbbell', 'weight_reps'],
  ['rear-delt-fly', 'Rear Delts', 'Dumbbell', 'weight_reps'],
  ['reverse-pec-deck', 'Rear Delts', 'Machine', 'weight_reps'],
  ['face-pull', 'Upper Back', 'Cable', 'weight_reps'],
  ['upright-row', 'Shoulders', 'Barbell', 'weight_reps'],
  ['deadlift', 'Posterior Chain', 'Barbell', 'weight_reps'],
  ['romanian-deadlift', 'Hamstrings', 'Barbell', 'weight_reps'],
  ['barbell-row', 'Back', 'Barbell', 'weight_reps'],
  ['t-bar-row', 'Back', 'Machine', 'weight_reps'],
  ['dumbbell-bent-over-row', 'Back', 'Dumbbell', 'weight_reps'],
  ['one-arm-dumbbell-row', 'Back', 'Dumbbell', 'weight_reps'],
  ['chest-supported-row', 'Back', 'Machine', 'weight_reps'],
  ['seated-row', 'Back', 'Cable', 'weight_reps'],
  ['machine-row', 'Back', 'Machine', 'weight_reps'],
  ['lat-pulldown', 'Lats', 'Cable', 'weight_reps'],
  ['close-grip-lat-pulldown', 'Lats', 'Cable', 'weight_reps'],
  ['straight-arm-pulldown', 'Lats', 'Cable', 'weight_reps'],
  ['pull-up', 'Lats', 'Bodyweight', 'bodyweight_reps'],
  ['assisted-pull-up', 'Lats', 'Machine', 'assisted_bodyweight'],
  ['weighted-pull-up', 'Lats', 'Bodyweight', 'weight_reps'],
  ['chin-up', 'Biceps', 'Bodyweight', 'bodyweight_reps'],
  ['shrug', 'Upper Back', 'Barbell', 'weight_reps'],
  ['squat', 'Quads', 'Barbell', 'weight_reps'],
  ['front-squat', 'Quads', 'Barbell', 'weight_reps'],
  ['hack-squat', 'Quads', 'Machine', 'weight_reps'],
  ['leg-press', 'Quads', 'Machine', 'weight_reps'],
  ['bulgarian-split-squat', 'Quads', 'Dumbbell', 'weight_reps'],
  ['walking-lunge', 'Quads', 'Dumbbell', 'weight_reps'],
  ['step-up', 'Quads', 'Dumbbell', 'weight_reps'],
  ['leg-extension', 'Quads', 'Machine', 'weight_reps'],
  ['leg-curl', 'Hamstrings', 'Machine', 'weight_reps'],
  ['seated-leg-curl', 'Hamstrings', 'Machine', 'weight_reps'],
  ['hip-thrust', 'Glutes', 'Barbell', 'weight_reps'],
  ['glute-bridge', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['good-morning', 'Hamstrings', 'Barbell', 'weight_reps'],
  ['standing-calf-raise', 'Calves', 'Machine', 'weight_reps'],
  ['seated-calf-raise', 'Calves', 'Machine', 'weight_reps'],
  ['bicep-curl', 'Biceps', 'Dumbbell', 'weight_reps'],
  ['hammer-curl', 'Biceps', 'Dumbbell', 'weight_reps'],
  ['preacher-curl', 'Biceps', 'Machine', 'weight_reps'],
  ['cable-curl', 'Biceps', 'Cable', 'weight_reps'],
  ['reverse-curl', 'Forearms', 'Barbell', 'weight_reps'],
  ['wrist-curl', 'Forearms', 'Barbell', 'weight_reps'],
  ['tricep-pushdown', 'Triceps', 'Cable', 'weight_reps'],
  ['overhead-tricep-extension', 'Triceps', 'Cable', 'weight_reps'],
  ['skull-crusher', 'Triceps', 'Barbell', 'weight_reps'],
  ['close-grip-bench-press', 'Triceps', 'Barbell', 'weight_reps'],
  ['dip', 'Triceps', 'Bodyweight', 'bodyweight_reps'],
  ['assisted-dip', 'Triceps', 'Machine', 'assisted_bodyweight'],
  ['plank', 'Core', 'Bodyweight', 'duration'],
  ['side-plank', 'Core', 'Bodyweight', 'duration'],
  ['hanging-leg-raise', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['cable-crunch', 'Core', 'Cable', 'weight_reps'],
  ['ab-wheel', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['running', 'Legs', 'Cardio', 'distance_duration'],
  ['walking', 'Legs', 'Cardio', 'distance_duration'],
  ['cycling', 'Legs', 'Cardio', 'distance_duration'],
  ['rowing', 'Back', 'Cardio', 'distance_duration'],
  ['stair-climber', 'Legs', 'Cardio', 'duration'],
  ['dumbbell-fly', 'Chest', 'Dumbbell', 'weight_reps'],
  ['incline-cable-fly', 'Chest', 'Cable', 'weight_reps'],
  ['decline-dumbbell-press', 'Chest', 'Dumbbell', 'weight_reps'],
  ['smith-machine-bench-press', 'Chest', 'Machine', 'weight_reps'],
  ['landmine-press', 'Shoulders', 'Barbell', 'weight_reps'],
  ['chest-dip', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['weighted-dip', 'Triceps', 'Bodyweight', 'weight_reps'],
  ['machine-shoulder-press', 'Shoulders', 'Machine', 'weight_reps'],
  ['standing-dumbbell-press', 'Shoulders', 'Dumbbell', 'weight_reps'],
  ['push-press', 'Shoulders', 'Barbell', 'weight_reps'],
  ['machine-lateral-raise', 'Shoulders', 'Machine', 'weight_reps'],
  ['cable-front-raise', 'Shoulders', 'Cable', 'weight_reps'],
  ['plate-front-raise', 'Shoulders', 'Plate', 'weight_reps'],
  ['bent-over-rear-delt-raise', 'Rear Delts', 'Dumbbell', 'weight_reps'],
  ['cable-rear-delt-fly', 'Rear Delts', 'Cable', 'weight_reps'],
  ['pendlay-row', 'Back', 'Barbell', 'weight_reps'],
  ['inverted-row', 'Back', 'Bodyweight', 'bodyweight_reps'],
  ['meadows-row', 'Back', 'Barbell', 'weight_reps'],
  ['single-arm-cable-row', 'Back', 'Cable', 'weight_reps'],
  ['wide-grip-lat-pulldown', 'Lats', 'Cable', 'weight_reps'],
  ['neutral-grip-pull-up', 'Lats', 'Bodyweight', 'bodyweight_reps'],
  ['assisted-chin-up', 'Biceps', 'Machine', 'assisted_bodyweight'],
  ['weighted-chin-up', 'Biceps', 'Bodyweight', 'weight_reps'],
  ['rack-pull', 'Back', 'Barbell', 'weight_reps'],
  ['back-extension', 'Lower Back', 'Bodyweight', 'bodyweight_reps'],
  ['dumbbell-shrug', 'Upper Back', 'Dumbbell', 'weight_reps'],
  ['goblet-squat', 'Quads', 'Dumbbell', 'weight_reps'],
  ['smith-machine-squat', 'Quads', 'Machine', 'weight_reps'],
  ['belt-squat', 'Quads', 'Machine', 'weight_reps'],
  ['sumo-deadlift', 'Posterior Chain', 'Barbell', 'weight_reps'],
  ['trap-bar-deadlift', 'Posterior Chain', 'Barbell', 'weight_reps'],
  ['lying-leg-curl', 'Hamstrings', 'Machine', 'weight_reps'],
  ['nordic-hamstring-curl', 'Hamstrings', 'Bodyweight', 'bodyweight_reps'],
  ['single-leg-romanian-deadlift', 'Hamstrings', 'Dumbbell', 'weight_reps'],
  ['reverse-lunge', 'Quads', 'Dumbbell', 'weight_reps'],
  ['split-squat', 'Quads', 'Dumbbell', 'weight_reps'],
  ['cable-kickback', 'Glutes', 'Cable', 'weight_reps'],
  ['hip-abduction-machine', 'Glutes', 'Machine', 'weight_reps'],
  ['single-leg-glute-bridge', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['barbell-glute-bridge', 'Glutes', 'Barbell', 'weight_reps'],
  ['dumbbell-glute-bridge', 'Glutes', 'Dumbbell', 'weight_reps'],
  ['dumbbell-hip-thrust', 'Glutes', 'Dumbbell', 'weight_reps'],
  ['smith-machine-hip-thrust', 'Glutes', 'Machine', 'weight_reps'],
  ['smith-machine-romanian-deadlift', 'Hamstrings', 'Machine', 'weight_reps'],
  ['dumbbell-romanian-deadlift', 'Hamstrings', 'Dumbbell', 'weight_reps'],
  ['kettlebell-romanian-deadlift', 'Hamstrings', 'Kettlebell', 'weight_reps'],
  ['cable-pull-through', 'Glutes', 'Cable', 'weight_reps'],
  ['machine-glute-kickback', 'Glutes', 'Machine', 'weight_reps'],
  ['cable-standing-hip-abduction', 'Glutes', 'Cable', 'weight_reps'],
  ['cable-standing-hip-adduction', 'Adductors', 'Cable', 'weight_reps'],
  ['hip-adduction-machine', 'Adductors', 'Machine', 'weight_reps'],
  ['smith-machine-bulgarian-split-squat', 'Quads', 'Machine', 'weight_reps'],
  ['smith-machine-reverse-lunge', 'Quads', 'Machine', 'weight_reps'],
  ['smith-machine-split-squat', 'Quads', 'Machine', 'weight_reps'],
  ['heel-elevated-goblet-squat', 'Quads', 'Dumbbell', 'weight_reps'],
  ['dumbbell-sumo-squat', 'Glutes', 'Dumbbell', 'weight_reps'],
  ['dumbbell-sumo-deadlift', 'Posterior Chain', 'Dumbbell', 'weight_reps'],
  ['front-foot-elevated-split-squat', 'Quads', 'Dumbbell', 'weight_reps'],
  ['deficit-reverse-lunge', 'Glutes', 'Dumbbell', 'weight_reps'],
  ['dumbbell-lateral-lunge', 'Quads', 'Dumbbell', 'weight_reps'],
  ['dumbbell-curtsy-lunge', 'Glutes', 'Dumbbell', 'weight_reps'],
  ['landmine-squat', 'Quads', 'Barbell', 'weight_reps'],
  ['landmine-romanian-deadlift', 'Hamstrings', 'Barbell', 'weight_reps'],
  ['kettlebell-swing', 'Glutes', 'Kettlebell', 'weight_reps'],
  ['glute-focused-back-extension', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['reverse-hyperextension', 'Glutes', 'Machine', 'bodyweight_reps'],
  ['donkey-calf-raise', 'Calves', 'Machine', 'weight_reps'],
  ['leg-press-calf-raise', 'Calves', 'Machine', 'weight_reps'],
  ['wall-sit', 'Quads', 'Bodyweight', 'duration'],
  ['jump-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['incline-dumbbell-curl', 'Biceps', 'Dumbbell', 'weight_reps'],
  ['concentration-curl', 'Biceps', 'Dumbbell', 'weight_reps'],
  ['ez-bar-curl', 'Biceps', 'Barbell', 'weight_reps'],
  ['spider-curl', 'Biceps', 'Dumbbell', 'weight_reps'],
  ['rope-hammer-curl', 'Biceps', 'Cable', 'weight_reps'],
  ['drag-curl', 'Biceps', 'Barbell', 'weight_reps'],
  ['rope-tricep-pushdown', 'Triceps', 'Cable', 'weight_reps'],
  ['dumbbell-skull-crusher', 'Triceps', 'Dumbbell', 'weight_reps'],
  ['single-dumbbell-skullcrusher', 'Triceps', 'Dumbbell', 'weight_reps'],
  ['dumbbell-overhead-tricep-extension', 'Triceps', 'Dumbbell', 'weight_reps'],
  ['single-arm-dumbbell-tricep-extension', 'Triceps', 'Dumbbell', 'weight_reps'],
  ['bench-dip', 'Triceps', 'Bodyweight', 'bodyweight_reps'],
  ['tricep-kickback', 'Triceps', 'Dumbbell', 'weight_reps'],
  ['wrist-extension', 'Forearms', 'Dumbbell', 'weight_reps'],
  ['farmer-carry', 'Forearms', 'Dumbbell', 'distance_duration'],
  ['crunch', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['reverse-crunch', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['russian-twist', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['bicycle-crunch', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['mountain-climber', 'Core', 'Bodyweight', 'duration'],
  ['dead-bug', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['bird-dog', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['pallof-press', 'Core', 'Cable', 'weight_reps'],
  ['cable-woodchop', 'Core', 'Cable', 'weight_reps'],
  ['half-kneeling-pallof-press', 'Core', 'Cable', 'weight_reps'],
  ['cable-pallof-hold', 'Core', 'Cable', 'duration'],
  ['hanging-knee-raise', 'Core', 'Pull-up Bar', 'bodyweight_reps'],
  ['captains-chair-knee-raise', 'Core', 'Machine', 'bodyweight_reps'],
  ['decline-sit-up', 'Core', 'Bench', 'bodyweight_reps'],
  ['weighted-crunch', 'Core', 'Plate', 'weight_reps'],
  ['weighted-russian-twist', 'Core', 'Dumbbell', 'weight_reps'],
  ['dumbbell-side-bend', 'Core', 'Dumbbell', 'weight_reps'],
  ['elliptical', 'Legs', 'Cardio', 'duration'],
  ['swimming', 'Back', 'Cardio', 'distance_duration'],
  ['jump-rope', 'Calves', 'Cardio', 'duration'],
  ['assault-bike', 'Legs', 'Cardio', 'distance_duration'],
  ['skierg', 'Back', 'Cardio', 'distance_duration'],
  ['hiking', 'Legs', 'Cardio', 'distance_duration'],
  ['treadmill-incline-walk', 'Legs', 'Cardio', 'distance_duration'],
  ['battle-ropes', 'Shoulders', 'Cardio', 'duration'],
  ['incline-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['knee-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['wide-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['diamond-push-up', 'Triceps', 'Bodyweight', 'bodyweight_reps'],
  ['decline-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['pike-push-up', 'Shoulders', 'Bodyweight', 'bodyweight_reps'],
  ['feet-elevated-pike-push-up', 'Shoulders', 'Bodyweight', 'bodyweight_reps'],
  ['archer-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['typewriter-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['explosive-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['hindu-push-up', 'Chest', 'Bodyweight', 'bodyweight_reps'],
  ['scapular-push-up', 'Upper Back', 'Bodyweight', 'bodyweight_reps'],
  ['push-up-shoulder-tap', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['wall-push-up', 'Chest', 'Wall', 'bodyweight_reps'],
  ['wall-walk', 'Shoulders', 'Wall', 'bodyweight_reps'],
  ['wall-handstand-push-up', 'Shoulders', 'Wall', 'bodyweight_reps'],
  ['handstand-push-up', 'Shoulders', 'Bodyweight', 'bodyweight_reps'],
  ['chair-dip', 'Triceps', 'Chair', 'bodyweight_reps'],
  ['doorway-row', 'Back', 'Doorway', 'bodyweight_reps'],
  ['towel-row', 'Back', 'Towel', 'bodyweight_reps'],
  ['prone-y-raise', 'Upper Back', 'Bodyweight', 'bodyweight_reps'],
  ['prone-t-raise', 'Upper Back', 'Bodyweight', 'bodyweight_reps'],
  ['superman', 'Lower Back', 'Bodyweight', 'bodyweight_reps'],
  ['superman-hold', 'Lower Back', 'Bodyweight', 'duration'],
  ['reverse-snow-angel', 'Upper Back', 'Bodyweight', 'bodyweight_reps'],
  ['dead-hang', 'Forearms', 'Pull-up Bar', 'duration'],
  ['active-hang', 'Lats', 'Pull-up Bar', 'duration'],
  ['scapular-pull-up', 'Lats', 'Pull-up Bar', 'bodyweight_reps'],
  ['negative-pull-up', 'Lats', 'Pull-up Bar', 'bodyweight_reps'],
  ['commando-pull-up', 'Lats', 'Pull-up Bar', 'bodyweight_reps'],
  ['l-sit-pull-up', 'Lats', 'Pull-up Bar', 'bodyweight_reps'],
  ['towel-pull-up', 'Lats', 'Towel', 'bodyweight_reps'],
  ['bodyweight-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['pistol-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['assisted-pistol-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['shrimp-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['cossack-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['sissy-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['forward-lunge', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['lateral-lunge', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['curtsy-lunge', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['skater-squat', 'Quads', 'Bodyweight', 'bodyweight_reps'],
  ['single-leg-box-squat', 'Quads', 'Box', 'bodyweight_reps'],
  ['step-down', 'Quads', 'Box', 'bodyweight_reps'],
  ['calf-raise', 'Calves', 'Bodyweight', 'bodyweight_reps'],
  ['single-leg-calf-raise', 'Calves', 'Bodyweight', 'bodyweight_reps'],
  ['glute-bridge-march', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['frog-pump', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['donkey-kick', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['fire-hydrant', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['clamshell', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['hip-airplane', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['side-lying-hip-abduction', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['side-lying-leg-raise', 'Glutes', 'Bodyweight', 'bodyweight_reps'],
  ['lying-hamstring-walkout', 'Hamstrings', 'Bodyweight', 'bodyweight_reps'],
  ['towel-hamstring-curl', 'Hamstrings', 'Towel', 'bodyweight_reps'],
  ['stability-ball-hamstring-curl', 'Hamstrings', 'Stability Ball', 'bodyweight_reps'],
  ['banded-glute-bridge', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-hip-thrust', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-frog-pump', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-clamshell', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-lateral-walk', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-monster-walk', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-squat', 'Quads', 'Resistance Band', 'bodyweight_reps'],
  ['banded-donkey-kick', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-fire-hydrant', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-kickback', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-standing-hip-abduction', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['banded-seated-hip-abduction', 'Glutes', 'Resistance Band', 'bodyweight_reps'],
  ['band-pull-apart', 'Upper Back', 'Resistance Band', 'bodyweight_reps'],
  ['banded-face-pull', 'Upper Back', 'Resistance Band', 'bodyweight_reps'],
  ['banded-row', 'Back', 'Resistance Band', 'bodyweight_reps'],
  ['banded-lat-pulldown', 'Lats', 'Resistance Band', 'bodyweight_reps'],
  ['banded-pallof-press', 'Core', 'Resistance Band', 'bodyweight_reps'],
  ['banded-woodchop', 'Core', 'Resistance Band', 'bodyweight_reps'],
  ['banded-dead-bug', 'Core', 'Resistance Band', 'bodyweight_reps'],
  ['hollow-body-hold', 'Core', 'Bodyweight', 'duration'],
  ['hollow-rock', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['v-up', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['flutter-kick', 'Core', 'Bodyweight', 'duration'],
  ['lying-leg-raise', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['toe-touch', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['heel-tap', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['plank-shoulder-tap', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['plank-jack', 'Core', 'Bodyweight', 'duration'],
  ['bear-plank', 'Core', 'Bodyweight', 'duration'],
  ['bear-crawl', 'Core', 'Bodyweight', 'duration'],
  ['crab-walk', 'Triceps', 'Bodyweight', 'duration'],
  ['inchworm', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['l-sit-hold', 'Core', 'Bodyweight', 'duration'],
  ['seated-knee-tuck', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['side-plank-hip-dip', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['copenhagen-plank', 'Core', 'Bodyweight', 'duration'],
  ['dragon-flag', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['burpee', 'Legs', 'Bodyweight', 'bodyweight_reps'],
  ['half-burpee', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['squat-thrust', 'Core', 'Bodyweight', 'bodyweight_reps'],
  ['high-knees', 'Legs', 'Bodyweight', 'duration'],
  ['jumping-jack', 'Legs', 'Bodyweight', 'duration'],
  ['skater-hop', 'Legs', 'Bodyweight', 'bodyweight_reps'],
  ['lateral-shuffle', 'Legs', 'Bodyweight', 'duration'],
  ['fast-feet', 'Calves', 'Bodyweight', 'duration'],
  ['sprawl', 'Legs', 'Bodyweight', 'bodyweight_reps'],
  ['seal-jack', 'Chest', 'Bodyweight', 'duration'],
];
