/**
 * O nome em portugues de cada movimento da biblioteca.
 *
 * Escrito a mao, e a unica parte da biblioteca que nao sai do manifesto. Vale a
 * mesma regra que `src/db/catalog.ts` ja fixa para os comuns: **um nome por
 * movimento, o mais reconhecivel no Brasil, sem sinonimo**. "Puxada alta" e nao
 * tambem "Pulley frente"; quem chama de outro jeito renomeia depois de
 * adicionar.
 *
 * Os 59 nomes que ja existem em `COMMON_EXERCISES` aparecem aqui identicos, de
 * proposito: e o que faz `findMovement` achar a figura de um exercicio que o
 * app semeou, e o que impede a biblioteca de oferecer um segundo "Supino reto".
 * `library.test.ts` quebra se algum sair do lugar.
 *
 * A chave e o slug do workout-guide. O agrupamento em secoes aqui e so para
 * leitura — o grupo de verdade sai de `taxonomy.ts`.
 */

export const NAMES_PT: Readonly<Record<string, string>> = {
  // ─── Peito ──────────────────────────────────────────────────────────────
  'bench-press': 'Supino reto',
  'incline-bench-press': 'Supino inclinado',
  'decline-bench-press': 'Supino declinado',
  'dumbbell-bench-press': 'Supino com halteres',
  'incline-dumbbell-press': 'Supino inclinado com halteres',
  'decline-dumbbell-press': 'Supino declinado com halteres',
  'smith-machine-bench-press': 'Supino no Smith',
  'machine-chest-press': 'Supino na máquina',
  'pec-deck': 'Peck deck',
  'dumbbell-fly': 'Crucifixo',
  'cable-fly': 'Crossover',
  'incline-cable-fly': 'Crossover inclinado',
  'chest-dip': 'Mergulho em paralelas',
  'push-up': 'Flexão de braço',
  'weighted-push-up': 'Flexão com peso',
  'knee-push-up': 'Flexão de joelhos',
  'incline-push-up': 'Flexão inclinada',
  'decline-push-up': 'Flexão declinada',
  'wide-push-up': 'Flexão aberta',
  'archer-push-up': 'Flexão arqueiro',
  'typewriter-push-up': 'Flexão deslizante',
  'explosive-push-up': 'Flexão explosiva',
  'hindu-push-up': 'Flexão hindu',
  'wall-push-up': 'Flexão na parede',
  'seal-jack': 'Polichinelo horizontal',

  // ─── Costas ─────────────────────────────────────────────────────────────
  deadlift: 'Levantamento terra',
  'sumo-deadlift': 'Terra sumô',
  'dumbbell-sumo-deadlift': 'Terra sumô com halteres',
  'trap-bar-deadlift': 'Terra com barra hexagonal',
  'rack-pull': 'Levantamento terra parcial',
  'barbell-row': 'Remada curvada',
  'dumbbell-bent-over-row': 'Remada curvada com halteres',
  't-bar-row': 'Remada cavalinho',
  'one-arm-dumbbell-row': 'Remada unilateral',
  'single-arm-cable-row': 'Remada unilateral na polia',
  'seated-row': 'Remada baixa',
  'machine-row': 'Remada na máquina',
  'chest-supported-row': 'Remada com apoio no peito',
  'pendlay-row': 'Remada Pendlay',
  'meadows-row': 'Remada Meadows',
  'inverted-row': 'Remada invertida',
  'doorway-row': 'Remada no batente',
  'towel-row': 'Remada com toalha',
  'banded-row': 'Remada com elástico',
  'lat-pulldown': 'Puxada alta',
  'wide-grip-lat-pulldown': 'Puxada aberta',
  'close-grip-lat-pulldown': 'Puxada fechada',
  'banded-lat-pulldown': 'Puxada com elástico',
  'straight-arm-pulldown': 'Pulldown',
  'pull-up': 'Barra fixa',
  'assisted-pull-up': 'Barra fixa assistida',
  'weighted-pull-up': 'Barra fixa com peso',
  'neutral-grip-pull-up': 'Barra fixa neutra',
  'negative-pull-up': 'Barra fixa negativa',
  'commando-pull-up': 'Barra fixa comando',
  'l-sit-pull-up': 'Barra fixa em L',
  'towel-pull-up': 'Barra fixa com toalha',
  'scapular-pull-up': 'Barra escapular',
  'active-hang': 'Suspensão ativa',
  shrug: 'Encolhimento',
  'dumbbell-shrug': 'Encolhimento com halteres',
  'back-extension': 'Extensão lombar',
  'scapular-push-up': 'Flexão escapular',
  'prone-y-raise': 'Elevação em Y',
  'prone-t-raise': 'Elevação em T',
  superman: 'Superman',
  'superman-hold': 'Superman isométrico',
  'reverse-snow-angel': 'Anjo invertido',
  'band-pull-apart': 'Abertura com elástico',
  'face-pull': 'Face pull',
  'banded-face-pull': 'Face pull com elástico',

  // ─── Pernas ─────────────────────────────────────────────────────────────
  squat: 'Agachamento livre',
  'front-squat': 'Agachamento frontal',
  'bodyweight-squat': 'Agachamento sem peso',
  'goblet-squat': 'Agachamento goblet',
  'heel-elevated-goblet-squat': 'Agachamento goblet com calço',
  'smith-machine-squat': 'Agachamento no Smith',
  'landmine-squat': 'Agachamento landmine',
  'belt-squat': 'Agachamento com cinto',
  'banded-squat': 'Agachamento com elástico',
  'jump-squat': 'Agachamento com salto',
  'pistol-squat': 'Agachamento pistol',
  'assisted-pistol-squat': 'Agachamento pistol assistido',
  'shrimp-squat': 'Agachamento shrimp',
  'cossack-squat': 'Agachamento cossaco',
  'sissy-squat': 'Agachamento sissy',
  'skater-squat': 'Agachamento patinador',
  'single-leg-box-squat': 'Agachamento unilateral no caixote',
  'hack-squat': 'Hack machine',
  'leg-press': 'Leg press',
  'leg-extension': 'Cadeira extensora',
  'seated-leg-curl': 'Cadeira flexora',
  'lying-leg-curl': 'Mesa flexora',
  'leg-curl': 'Flexora em pé',
  'towel-hamstring-curl': 'Flexora com toalha',
  'stability-ball-hamstring-curl': 'Flexora na bola',
  'nordic-hamstring-curl': 'Flexão nórdica',
  'lying-hamstring-walkout': 'Caminhada de posterior deitado',
  'romanian-deadlift': 'Stiff',
  'dumbbell-romanian-deadlift': 'Stiff com halteres',
  'kettlebell-romanian-deadlift': 'Stiff com kettlebell',
  'smith-machine-romanian-deadlift': 'Stiff no Smith',
  'landmine-romanian-deadlift': 'Stiff landmine',
  'single-leg-romanian-deadlift': 'Stiff unilateral',
  'good-morning': 'Bom dia',
  'forward-lunge': 'Afundo',
  'reverse-lunge': 'Afundo para trás',
  'walking-lunge': 'Afundo caminhando',
  'lateral-lunge': 'Afundo lateral',
  'dumbbell-lateral-lunge': 'Afundo lateral com halteres',
  'split-squat': 'Afundo estático',
  'smith-machine-split-squat': 'Afundo estático no Smith',
  'smith-machine-reverse-lunge': 'Afundo para trás no Smith',
  'front-foot-elevated-split-squat': 'Afundo com pé elevado',
  'bulgarian-split-squat': 'Búlgaro',
  'smith-machine-bulgarian-split-squat': 'Búlgaro no Smith',
  'step-up': 'Subida no caixote',
  'step-down': 'Descida do caixote',
  'standing-calf-raise': 'Panturrilha em pé',
  'seated-calf-raise': 'Panturrilha sentado',
  'donkey-calf-raise': 'Panturrilha burrinho',
  'leg-press-calf-raise': 'Panturrilha no leg press',
  'calf-raise': 'Panturrilha sem peso',
  'single-leg-calf-raise': 'Panturrilha unilateral',
  'hip-adduction-machine': 'Cadeira adutora',
  'hip-abduction-machine': 'Cadeira abdutora',
  'cable-standing-hip-adduction': 'Adução na polia',
  'wall-sit': 'Cadeirinha na parede',
  burpee: 'Burpee',
  'high-knees': 'Joelhos altos',
  'jumping-jack': 'Polichinelo',
  'skater-hop': 'Salto patinador',
  'lateral-shuffle': 'Deslocamento lateral',
  'fast-feet': 'Pés rápidos',
  sprawl: 'Sprawl',

  // ─── Glúteos ────────────────────────────────────────────────────────────
  'hip-thrust': 'Elevação pélvica',
  'dumbbell-hip-thrust': 'Elevação pélvica com halter',
  'smith-machine-hip-thrust': 'Elevação pélvica no Smith',
  'banded-hip-thrust': 'Elevação pélvica com elástico',
  'glute-bridge': 'Ponte de glúteo',
  'single-leg-glute-bridge': 'Ponte de glúteo unilateral',
  'barbell-glute-bridge': 'Ponte de glúteo com barra',
  'dumbbell-glute-bridge': 'Ponte de glúteo com halter',
  'banded-glute-bridge': 'Ponte de glúteo com elástico',
  'glute-bridge-march': 'Ponte de glúteo com marcha',
  'frog-pump': 'Ponte de rã',
  'banded-frog-pump': 'Ponte de rã com elástico',
  'cable-kickback': 'Glúteo na polia',
  'machine-glute-kickback': 'Coice na máquina',
  'donkey-kick': 'Coice de quatro apoios',
  'banded-donkey-kick': 'Coice com elástico',
  'banded-kickback': 'Coice em pé com elástico',
  'cable-pull-through': 'Pull through na polia',
  'cable-standing-hip-abduction': 'Abdução na polia',
  'banded-standing-hip-abduction': 'Abdução em pé com elástico',
  'banded-seated-hip-abduction': 'Abdução sentado com elástico',
  'side-lying-hip-abduction': 'Abdução deitado de lado',
  'side-lying-leg-raise': 'Elevação lateral de perna',
  'fire-hydrant': 'Abdução de quatro apoios',
  'banded-fire-hydrant': 'Abdução de quatro apoios com elástico',
  clamshell: 'Concha',
  'banded-clamshell': 'Concha com elástico',
  'banded-lateral-walk': 'Caminhada lateral com elástico',
  'banded-monster-walk': 'Caminhada monstro com elástico',
  'curtsy-lunge': 'Afundo cruzado',
  'dumbbell-curtsy-lunge': 'Afundo cruzado com halteres',
  'deficit-reverse-lunge': 'Afundo para trás com déficit',
  'dumbbell-sumo-squat': 'Agachamento sumô com halter',
  'kettlebell-swing': 'Swing com kettlebell',
  'glute-focused-back-extension': 'Extensão lombar para glúteo',
  'reverse-hyperextension': 'Hiperextensão invertida',
  'hip-airplane': 'Avião de quadril',

  // ─── Ombros ─────────────────────────────────────────────────────────────
  'overhead-press': 'Desenvolvimento',
  'arnold-press': 'Desenvolvimento Arnold',
  'seated-dumbbell-press': 'Desenvolvimento sentado com halteres',
  'standing-dumbbell-press': 'Desenvolvimento em pé com halteres',
  'machine-shoulder-press': 'Desenvolvimento na máquina',
  'landmine-press': 'Desenvolvimento landmine',
  'push-press': 'Desenvolvimento com impulso',
  'lateral-raise': 'Elevação lateral',
  'cable-lateral-raise': 'Elevação lateral na polia',
  'machine-lateral-raise': 'Elevação lateral na máquina',
  'front-raise': 'Elevação frontal',
  'cable-front-raise': 'Elevação frontal na polia',
  'plate-front-raise': 'Elevação frontal com anilha',
  'rear-delt-fly': 'Crucifixo inverso',
  'bent-over-rear-delt-raise': 'Crucifixo inverso curvado',
  'cable-rear-delt-fly': 'Crucifixo inverso na polia',
  'reverse-pec-deck': 'Peck deck inverso',
  'upright-row': 'Remada alta',
  'pike-push-up': 'Flexão pique',
  'feet-elevated-pike-push-up': 'Flexão pique com pés elevados',
  'handstand-push-up': 'Flexão de parada de mão',
  'wall-handstand-push-up': 'Flexão de parada na parede',
  'wall-walk': 'Caminhada na parede',

  // ─── Bíceps ─────────────────────────────────────────────────────────────
  'ez-bar-curl': 'Rosca direta',
  'bicep-curl': 'Rosca alternada',
  'hammer-curl': 'Rosca martelo',
  'rope-hammer-curl': 'Rosca martelo na corda',
  'preacher-curl': 'Rosca scott',
  'concentration-curl': 'Rosca concentrada',
  'cable-curl': 'Rosca na polia',
  'incline-dumbbell-curl': 'Rosca inclinada',
  'spider-curl': 'Rosca spider',
  'drag-curl': 'Rosca arrasto',
  'reverse-curl': 'Rosca inversa',
  'wrist-curl': 'Rosca de punho',
  'wrist-extension': 'Extensão de punho',
  'chin-up': 'Barra fixa supinada',
  'assisted-chin-up': 'Barra supinada assistida',
  'weighted-chin-up': 'Barra supinada com peso',
  'dead-hang': 'Suspensão passiva',

  // ─── Tríceps ────────────────────────────────────────────────────────────
  'tricep-pushdown': 'Tríceps barra',
  'rope-tricep-pushdown': 'Tríceps corda',
  'skull-crusher': 'Tríceps testa',
  'dumbbell-skull-crusher': 'Tríceps testa com halteres',
  'single-dumbbell-skullcrusher': 'Tríceps testa com um halter',
  'overhead-tricep-extension': 'Tríceps francês',
  'dumbbell-overhead-tricep-extension': 'Tríceps francês com halteres',
  'single-arm-dumbbell-tricep-extension': 'Tríceps francês unilateral',
  'tricep-kickback': 'Tríceps coice',
  'close-grip-bench-press': 'Supino fechado',
  dip: 'Mergulho',
  'assisted-dip': 'Mergulho assistido',
  'weighted-dip': 'Mergulho com peso',
  'bench-dip': 'Mergulho no banco',
  'chair-dip': 'Mergulho na cadeira',
  'diamond-push-up': 'Flexão diamante',
  'crab-walk': 'Caminhada do caranguejo',

  // ─── Abdômen ────────────────────────────────────────────────────────────
  crunch: 'Abdominal supra',
  'reverse-crunch': 'Abdominal infra',
  'weighted-crunch': 'Abdominal supra com anilha',
  'cable-crunch': 'Abdominal na polia',
  'bicycle-crunch': 'Abdominal bicicleta',
  'decline-sit-up': 'Abdominal declinado',
  'seated-knee-tuck': 'Abdominal sentado',
  'v-up': 'Abdominal em V',
  'toe-touch': 'Abdominal toque no pé',
  'heel-tap': 'Toque no calcanhar',
  'russian-twist': 'Abdominal russo',
  'weighted-russian-twist': 'Abdominal russo com peso',
  'lying-leg-raise': 'Elevação de pernas',
  'hanging-leg-raise': 'Elevação de pernas na barra',
  'hanging-knee-raise': 'Elevação de joelhos na barra',
  'captains-chair-knee-raise': 'Elevação de joelhos na paralela',
  'flutter-kick': 'Tesoura vertical',
  plank: 'Prancha',
  'side-plank': 'Prancha lateral',
  'side-plank-hip-dip': 'Prancha lateral com queda de quadril',
  'plank-shoulder-tap': 'Prancha com toque no ombro',
  'plank-jack': 'Prancha com salto',
  'bear-plank': 'Prancha de urso',
  'copenhagen-plank': 'Prancha de Copenhague',
  'push-up-shoulder-tap': 'Flexão com toque no ombro',
  'bear-crawl': 'Caminhada do urso',
  inchworm: 'Minhoca',
  'mountain-climber': 'Escalador',
  'dead-bug': 'Inseto morto',
  'banded-dead-bug': 'Inseto morto com elástico',
  'bird-dog': 'Bird dog',
  'ab-wheel': 'Roda abdominal',
  'hollow-body-hold': 'Hollow isométrico',
  'hollow-rock': 'Hollow com balanço',
  'l-sit-hold': 'L-sit isométrico',
  'dragon-flag': 'Dragon flag',
  'dumbbell-side-bend': 'Flexão lateral com halter',
  'pallof-press': 'Pallof press',
  'half-kneeling-pallof-press': 'Pallof press ajoelhado',
  'cable-pallof-hold': 'Pallof isométrico',
  'banded-pallof-press': 'Pallof press com elástico',
  'cable-woodchop': 'Lenhador na polia',
  'banded-woodchop': 'Lenhador com elástico',
  'half-burpee': 'Meio burpee',
  'squat-thrust': 'Agachamento com projeção',

  // ─── Cardio ─────────────────────────────────────────────────────────────
  // "Corrida" precisa bater exatamente com o nome que `ensureRunExercise` cria
  // em src/db/repo.ts, senao a biblioteca ofereceria uma segunda corrida.
  running: 'Corrida',
  walking: 'Caminhada',
  'treadmill-incline-walk': 'Caminhada inclinada na esteira',
  hiking: 'Trilha',
  cycling: 'Bicicleta',
  'assault-bike': 'Bike assault',
  rowing: 'Remo ergômetro',
  skierg: 'SkiErg',
  swimming: 'Natação',
  'stair-climber': 'Escada ergométrica',
  elliptical: 'Elíptico',
  'jump-rope': 'Pular corda',
  'battle-ropes': 'Corda naval',
  'farmer-carry': 'Caminhada do fazendeiro',
};
